seed: 1337
device: "cpu"         # auto-falls back to cpu
num_workers: 0

# paths (point these to your folders)
paths:
  train_dir: "data/Train"
  val_dir:   "data/Val"
  test_dir:  "data/Test"
  ckpt_dir:  "checkpoints"

# training
epochs: 50
runtime:
  runtime:
  print_every: 20
  limit_train_pct: null     
  max_train_batches: null   
  max_val_batches: null     
batch_size: 32
lr: 1.0e-4
weight_decay: 0.0

# streams
rl:
  image_size: 128
  pretrained: true     
pl1:
  image_size: 224
  pretrained: true

# fusion
fusion:
  weights: null         # null = infer from per-stream val accuracy; else e.g. [0.4, 0.6]
